---
- name: Example playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Gebruik een variabele
      debug:
        msg: "Hostname: {{ item }}, Variable: {{ variable_2 }}"
      with_items: "{{ var_hosts }}"
